import { createMapFn } from 'map-fn';

import { ClubTeam, ClubCompetition, Team } from '../../../types/soccer.ts';

let teamId = 0;

function createTeam(team: Omit<Team, 'id'>): Team {
  return { id: ++teamId, ...team };
}

function createClubTeam(team: Omit<Team, 'id'> & { country: ClubCompetition }): ClubTeam {
  const { country, ...restTeam } = team;
  return { ...createTeam(restTeam), country };
}

// Premier League and EFL Championship, ordered by 2025/2026 season final standings
const englandClubs: Array<ClubTeam> = [
  createClubTeam({ name: 'Арсенал', shortName: 'АРС', country: 'england' }),
  createClubTeam({ name: 'Манчестер Сити', shortName: 'МСИ', country: 'england' }),
  createClubTeam({ name: 'Манчестер Юнайтед', shortName: 'МЮН', country: 'england' }),
  createClubTeam({ name: 'Астон Вилла', shortName: 'АВИ', country: 'england' }),
  createClubTeam({ name: 'Ливерпуль', shortName: 'ЛИВ', country: 'england' }),
  createClubTeam({ name: 'Борнмут', shortName: 'БОР', country: 'england' }),
  createClubTeam({ name: 'Сандерленд', shortName: 'САН', country: 'england' }),
  createClubTeam({ name: 'Брайтон', shortName: 'БРА', country: 'england' }),
  createClubTeam({ name: 'Брентфорд', shortName: 'БРЕ', country: 'england' }),
  createClubTeam({ name: 'Челси', shortName: 'ЧЕЛ', country: 'england' }),
  createClubTeam({ name: 'Фулхэм', shortName: 'ФУЛ', country: 'england' }),
  createClubTeam({ name: 'Ньюкасл Юнайтед', shortName: 'НЬЮ', country: 'england' }),
  createClubTeam({ name: 'Эвертон', shortName: 'ЭВЕ', country: 'england' }),
  createClubTeam({ name: 'Лидс Юнайтед', shortName: 'ЛИД', country: 'england' }),
  createClubTeam({ name: 'Кристал Пэлас', shortName: 'КРИ', country: 'england' }),
  createClubTeam({ name: 'Ноттингем Форест', shortName: 'НОТ', country: 'england' }),
  createClubTeam({ name: 'Тоттенхэм', shortName: 'ТОТ', country: 'england' }),
  createClubTeam({ name: 'Вест Хэм', shortName: 'ВХЭ', country: 'england' }),
  createClubTeam({ name: 'Бёрнли', shortName: 'БЕР', country: 'england' }),
  createClubTeam({ name: 'Вулверхэмптон', shortName: 'ВУЛ', country: 'england' }),
  createClubTeam({ name: 'Ковентри', shortName: 'КОВ', country: 'england' }),
  createClubTeam({ name: 'Ипсвич', shortName: 'ИПС', country: 'england' }),
  createClubTeam({ name: 'Миллуолл', shortName: 'МИЛ', country: 'england' }),
  createClubTeam({ name: 'Саутгемптон', shortName: 'САУ', country: 'england' }),
  createClubTeam({ name: 'Мидлсбро', shortName: 'МСБ', country: 'england' }),
  createClubTeam({ name: 'Халл Сити', shortName: 'ХАЛ', country: 'england' }),
  createClubTeam({ name: 'Рексхэм', shortName: 'РЕК', country: 'england' }),
  createClubTeam({ name: 'Дерби', shortName: 'ДЕР', country: 'england' }),
  createClubTeam({ name: 'Норвич', shortName: 'НОР', country: 'england' }),
  createClubTeam({ name: 'Бирмингем', shortName: 'БИР', country: 'england' }),
  createClubTeam({ name: 'Суонси', shortName: 'СУО', country: 'england' }),
  createClubTeam({ name: 'Бристоль Сити', shortName: 'БРИ', country: 'england' }),
  createClubTeam({ name: 'Шеффилд Юнайтед', shortName: 'ШЕФ', country: 'england' }),
  createClubTeam({ name: 'Престон', shortName: 'ПРЕ', country: 'england' }),
  createClubTeam({ name: 'Куинз Парк Рейнджерс', shortName: 'КПР', country: 'england' }),
  createClubTeam({ name: 'Уотфорд', shortName: 'УОТ', country: 'england' }),
  createClubTeam({ name: 'Сток Сити', shortName: 'СТО', country: 'england' }),
  createClubTeam({ name: 'Портсмут', shortName: 'ПОР', country: 'england' }),
  createClubTeam({ name: 'Чарльтон', shortName: 'ЧАР', country: 'england' }),
  createClubTeam({ name: 'Блэкберн', shortName: 'БЛЭ', country: 'england' }),
  createClubTeam({ name: 'Вест Бромвич', shortName: 'ВБР', country: 'england' }),
  createClubTeam({ name: 'Оксфорд Юнайтед', shortName: 'ОКС', country: 'england' }),
  createClubTeam({ name: 'Лестер', shortName: 'ЛЕС', country: 'england' }),
  createClubTeam({ name: 'Шеффилд Уэнсдей', shortName: 'ШЕВ', country: 'england' })
];

// Bundesliga and 2. Bundesliga, ordered by 2025/2026 season final standings
const germanyClubs: Array<ClubTeam> = [
  createClubTeam({ name: 'Бавария', shortName: 'БАВ', country: 'germany' }),
  createClubTeam({ name: 'Боруссия Дортмунд', shortName: 'БДО', country: 'germany' }),
  createClubTeam({ name: 'РБ Лейпциг', shortName: 'РБЛ', country: 'germany' }),
  createClubTeam({ name: 'Штутгарт', shortName: 'ШТУ', country: 'germany' }),
  createClubTeam({ name: 'Хоффенхайм', shortName: 'ХОФ', country: 'germany' }),
  createClubTeam({ name: 'Байер Леверкузен', shortName: 'БАЙ', country: 'germany' }),
  createClubTeam({ name: 'Фрайбург', shortName: 'ФРА', country: 'germany' }),
  createClubTeam({ name: 'Айнтрахт Франкфурт', shortName: 'АЙФ', country: 'germany' }),
  createClubTeam({ name: 'Аугсбург', shortName: 'АУГ', country: 'germany' }),
  createClubTeam({ name: 'Майнц', shortName: 'МАЙ', country: 'germany' }),
  createClubTeam({ name: 'Унион Берлин', shortName: 'УНИ', country: 'germany' }),
  createClubTeam({ name: 'Боруссия Мёнхенгладбах', shortName: 'БМГ', country: 'germany' }),
  createClubTeam({ name: 'Гамбург', shortName: 'ГАМ', country: 'germany' }),
  createClubTeam({ name: 'Кёльн', shortName: 'КЕЛ', country: 'germany' }),
  createClubTeam({ name: 'Вердер Бремен', shortName: 'ВЕР', country: 'germany' }),
  createClubTeam({ name: 'Вольфсбург', shortName: 'ВОЛ', country: 'germany' }),
  createClubTeam({ name: 'Хайденхайм', shortName: 'ХАЙ', country: 'germany' }),
  createClubTeam({ name: 'Санкт-Паули', shortName: 'СПА', country: 'germany' }),
  createClubTeam({ name: 'Шальке', shortName: 'ШАЛ', country: 'germany' }),
  createClubTeam({ name: 'Эльверсберг', shortName: 'ЭЛЬ', country: 'germany' }),
  createClubTeam({ name: 'Падерборн', shortName: 'ПАД', country: 'germany' }),
  createClubTeam({ name: 'Ганновер', shortName: 'ГАН', country: 'germany' }),
  createClubTeam({ name: 'Дармштадт', shortName: 'ДАР', country: 'germany' }),
  createClubTeam({ name: 'Кайзерслаутерн', shortName: 'КАЙ', country: 'germany' }),
  createClubTeam({ name: 'Герта', shortName: 'ГЕР', country: 'germany' }),
  createClubTeam({ name: 'Нюрнберг', shortName: 'НЮР', country: 'germany' }),
  createClubTeam({ name: 'Бохум', shortName: 'БОХ', country: 'germany' }),
  createClubTeam({ name: 'Карлсруэ', shortName: 'КАР', country: 'germany' }),
  createClubTeam({ name: 'Динамо Дрезден', shortName: 'ДИН', country: 'germany' }),
  createClubTeam({ name: 'Хольштайн Киль', shortName: 'ХОЛ', country: 'germany' }),
  createClubTeam({ name: 'Арминия Билефельд', shortName: 'АРМ', country: 'germany' }),
  createClubTeam({ name: 'Магдебург', shortName: 'МАГ', country: 'germany' }),
  createClubTeam({ name: 'Айнтрахт Брауншвейг', shortName: 'АЙБ', country: 'germany' }),
  createClubTeam({ name: 'Гройтер Фюрт', shortName: 'ГРО', country: 'germany' }),
  createClubTeam({ name: 'Фортуна Дюссельдорф', shortName: 'ФОР', country: 'germany' }),
  createClubTeam({ name: 'Пройсен Мюнстер', shortName: 'ПРО', country: 'germany' })
];

// La Liga and Segunda División, ordered by 2025/2026 season final standings
const spainClubs: Array<ClubTeam> = [
  createClubTeam({ name: 'Барселона', shortName: 'БАР', country: 'spain' }),
  createClubTeam({ name: 'Реал Мадрид', shortName: 'РЕА', country: 'spain' }),
  createClubTeam({ name: 'Вильярреал', shortName: 'ВИЛ', country: 'spain' }),
  createClubTeam({ name: 'Атлетико Мадрид', shortName: 'АТМ', country: 'spain' }),
  createClubTeam({ name: 'Реал Бетис', shortName: 'БЕТ', country: 'spain' }),
  createClubTeam({ name: 'Сельта', shortName: 'СЕЛ', country: 'spain' }),
  createClubTeam({ name: 'Хетафе', shortName: 'ХЕТ', country: 'spain' }),
  createClubTeam({ name: 'Райо Вальекано', shortName: 'РАЙ', country: 'spain' }),
  createClubTeam({ name: 'Валенсия', shortName: 'ВАЛ', country: 'spain' }),
  createClubTeam({ name: 'Реал Сосьедад', shortName: 'СОС', country: 'spain' }),
  createClubTeam({ name: 'Эспаньол', shortName: 'ЭСП', country: 'spain' }),
  createClubTeam({ name: 'Атлетик Бильбао', shortName: 'АТБ', country: 'spain' }),
  createClubTeam({ name: 'Севилья', shortName: 'СЕВ', country: 'spain' }),
  createClubTeam({ name: 'Алавес', shortName: 'АЛА', country: 'spain' }),
  createClubTeam({ name: 'Эльче', shortName: 'ЭЛЧ', country: 'spain' }),
  createClubTeam({ name: 'Леванте', shortName: 'ЛЕВ', country: 'spain' }),
  createClubTeam({ name: 'Осасуна', shortName: 'ОСА', country: 'spain' }),
  createClubTeam({ name: 'Мальорка', shortName: 'МАЛ', country: 'spain' }),
  createClubTeam({ name: 'Жирона', shortName: 'ЖИР', country: 'spain' }),
  createClubTeam({ name: 'Реал Овьедо', shortName: 'ОВЬ', country: 'spain' }),
  createClubTeam({ name: 'Расинг Сантандер', shortName: 'РАС', country: 'spain' }),
  createClubTeam({ name: 'Депортиво Ла Корунья', shortName: 'ДЕП', country: 'spain' }),
  createClubTeam({ name: 'Альмерия', shortName: 'АЛЬ', country: 'spain' }),
  createClubTeam({ name: 'Малага', shortName: 'МАГ', country: 'spain' }),
  createClubTeam({ name: 'Лас-Пальмас', shortName: 'ЛАП', country: 'spain' }),
  createClubTeam({ name: 'Кастельон', shortName: 'КАС', country: 'spain' }),
  createClubTeam({ name: 'Бургос', shortName: 'БУР', country: 'spain' }),
  createClubTeam({ name: 'Эйбар', shortName: 'ЭЙБ', country: 'spain' }),
  createClubTeam({ name: 'Кордоба', shortName: 'КОР', country: 'spain' }),
  createClubTeam({ name: 'Спортинг Хихон', shortName: 'СПХ', country: 'spain' }),
  createClubTeam({ name: 'Сеута', shortName: 'СЕУ', country: 'spain' }),
  createClubTeam({ name: 'Альбасете', shortName: 'АЛБ', country: 'spain' }),
  createClubTeam({ name: 'Андорра', shortName: 'АНД', country: 'spain' }),
  createClubTeam({ name: 'Гранада', shortName: 'ГРА', country: 'spain' }),
  createClubTeam({ name: 'Реал Сосьедад Б', shortName: 'СОБ', country: 'spain' }),
  createClubTeam({ name: 'Леганес', shortName: 'ЛЕГ', country: 'spain' }),
  createClubTeam({ name: 'Реал Вальядолид', shortName: 'ВАЛЬ', country: 'spain' }),
  createClubTeam({ name: 'Кадис', shortName: 'КАД', country: 'spain' }),
  createClubTeam({ name: 'Мирандес', shortName: 'МИР', country: 'spain' }),
  createClubTeam({ name: 'Уэска', shortName: 'УЭС', country: 'spain' }),
  createClubTeam({ name: 'Культураль Леонеса', shortName: 'КУЛ', country: 'spain' }),
  createClubTeam({ name: 'Реал Сарагоса', shortName: 'САР', country: 'spain' })
];

// Serie A and Serie B, ordered by 2025/2026 season final standings
const italyClubs: Array<ClubTeam> = [
  createClubTeam({ name: 'Интер', shortName: 'ИНТ', country: 'italy' }),
  createClubTeam({ name: 'Наполи', shortName: 'НАП', country: 'italy' }),
  createClubTeam({ name: 'Рома', shortName: 'РОМ', country: 'italy' }),
  createClubTeam({ name: 'Комо', shortName: 'КОМ', country: 'italy' }),
  createClubTeam({ name: 'Милан', shortName: 'МИЛ', country: 'italy' }),
  createClubTeam({ name: 'Ювентус', shortName: 'ЮВЕ', country: 'italy' }),
  createClubTeam({ name: 'Аталанта', shortName: 'АТА', country: 'italy' }),
  createClubTeam({ name: 'Болонья', shortName: 'БОЛ', country: 'italy' }),
  createClubTeam({ name: 'Лацио', shortName: 'ЛАЦ', country: 'italy' }),
  createClubTeam({ name: 'Удинезе', shortName: 'УДИ', country: 'italy' }),
  createClubTeam({ name: 'Сассуоло', shortName: 'САС', country: 'italy' }),
  createClubTeam({ name: 'Торино', shortName: 'ТОР', country: 'italy' }),
  createClubTeam({ name: 'Парма', shortName: 'ПАР', country: 'italy' }),
  createClubTeam({ name: 'Кальяри', shortName: 'КАЛ', country: 'italy' }),
  createClubTeam({ name: 'Фиорентина', shortName: 'ФИО', country: 'italy' }),
  createClubTeam({ name: 'Генуя', shortName: 'ГЕН', country: 'italy' }),
  createClubTeam({ name: 'Лечче', shortName: 'ЛЕЧ', country: 'italy' }),
  createClubTeam({ name: 'Кремонезе', shortName: 'КРЕ', country: 'italy' }),
  createClubTeam({ name: 'Верона', shortName: 'ВЕР', country: 'italy' }),
  createClubTeam({ name: 'Пиза', shortName: 'ПИЗ', country: 'italy' }),
  createClubTeam({ name: 'Венеция', shortName: 'ВЕН', country: 'italy' }),
  createClubTeam({ name: 'Фрозиноне', shortName: 'ФРО', country: 'italy' }),
  createClubTeam({ name: 'Монца', shortName: 'МОН', country: 'italy' }),
  createClubTeam({ name: 'Палермо', shortName: 'ПАЛ', country: 'italy' }),
  createClubTeam({ name: 'Катандзаро', shortName: 'КАТ', country: 'italy' }),
  createClubTeam({ name: 'Модена', shortName: 'МОД', country: 'italy' }),
  createClubTeam({ name: 'Юве Стабия', shortName: 'ЮСТ', country: 'italy' }),
  createClubTeam({ name: 'Авеллино', shortName: 'АВЕ', country: 'italy' }),
  createClubTeam({ name: 'Мантова', shortName: 'МАН', country: 'italy' }),
  createClubTeam({ name: 'Падова', shortName: 'ПАД', country: 'italy' }),
  createClubTeam({ name: 'Чезена', shortName: 'ЧЕЗ', country: 'italy' }),
  createClubTeam({ name: 'Каррарезе', shortName: 'КАР', country: 'italy' }),
  createClubTeam({ name: 'Сампдория', shortName: 'САМ', country: 'italy' }),
  createClubTeam({ name: 'Виртус Энтелла', shortName: 'ВИР', country: 'italy' }),
  createClubTeam({ name: 'Эмполи', shortName: 'ЭМП', country: 'italy' }),
  createClubTeam({ name: 'Зюдтироль', shortName: 'ЗЮД', country: 'italy' }),
  createClubTeam({ name: 'Бари', shortName: 'БАР', country: 'italy' }),
  createClubTeam({ name: 'Реджана', shortName: 'РЕД', country: 'italy' }),
  createClubTeam({ name: 'Специя', shortName: 'СПЕ', country: 'italy' }),
  createClubTeam({ name: 'Пескара', shortName: 'ПЕС', country: 'italy' })
];

// Ligue 1 and Ligue 2, ordered by 2025/2026 season final standings
const franceClubs: Array<ClubTeam> = [
  createClubTeam({ name: 'ПСЖ', shortName: 'ПСЖ', country: 'france' }),
  createClubTeam({ name: 'Ланс', shortName: 'ЛАН', country: 'france' }),
  createClubTeam({ name: 'Лилль', shortName: 'ЛИЛ', country: 'france' }),
  createClubTeam({ name: 'Олимпик Лион', shortName: 'ОЛ', country: 'france' }),
  createClubTeam({ name: 'Олимпик Марсель', shortName: 'ОМ', country: 'france' }),
  createClubTeam({ name: 'Ренн', shortName: 'РЕН', country: 'france' }),
  createClubTeam({ name: 'Монако', shortName: 'МОН', country: 'france' }),
  createClubTeam({ name: 'Страсбур', shortName: 'СТР', country: 'france' }),
  createClubTeam({ name: 'Тулуза', shortName: 'ТУЛ', country: 'france' }),
  createClubTeam({ name: 'Лорьян', shortName: 'ЛОР', country: 'france' }),
  createClubTeam({ name: 'Пари ФК', shortName: 'ПФК', country: 'france' }),
  createClubTeam({ name: 'Брест', shortName: 'БРЕ', country: 'france' }),
  createClubTeam({ name: 'Анже', shortName: 'АНЖ', country: 'france' }),
  createClubTeam({ name: 'Гавр', shortName: 'ГАВ', country: 'france' }),
  createClubTeam({ name: 'Осер', shortName: 'ОСЕ', country: 'france' }),
  createClubTeam({ name: 'Ницца', shortName: 'НИЦ', country: 'france' }),
  createClubTeam({ name: 'Нант', shortName: 'НАН', country: 'france' }),
  createClubTeam({ name: 'Мец', shortName: 'МЕЦ', country: 'france' }),
  createClubTeam({ name: 'Труа', shortName: 'ТРУ', country: 'france' }),
  createClubTeam({ name: 'Ле Ман', shortName: 'ЛЕМ', country: 'france' }),
  createClubTeam({ name: 'Сент-Этьен', shortName: 'СЭТ', country: 'france' }),
  createClubTeam({ name: 'Ред Стар', shortName: 'РЕД', country: 'france' }),
  createClubTeam({ name: 'Родез', shortName: 'РОД', country: 'france' }),
  createClubTeam({ name: 'Реймс', shortName: 'РЕЙ', country: 'france' }),
  createClubTeam({ name: 'Анси', shortName: 'АНС', country: 'france' }),
  createClubTeam({ name: 'Монпелье', shortName: 'МОП', country: 'france' }),
  createClubTeam({ name: 'По', shortName: 'ПОФ', country: 'france' }),
  createClubTeam({ name: 'Дюнкерк', shortName: 'ДЮН', country: 'france' }),
  createClubTeam({ name: 'Генган', shortName: 'ГЕН', country: 'france' }),
  createClubTeam({ name: 'Гренобль', shortName: 'ГРЕ', country: 'france' }),
  createClubTeam({ name: 'Клермон', shortName: 'КЛЕ', country: 'france' }),
  createClubTeam({ name: 'Нанси', shortName: 'НСИ', country: 'france' }),
  createClubTeam({ name: 'Булонь', shortName: 'БУЛ', country: 'france' }),
  createClubTeam({ name: 'Лаваль', shortName: 'ЛАВ', country: 'france' }),
  createClubTeam({ name: 'Бастия', shortName: 'БАС', country: 'france' }),
  createClubTeam({ name: 'Амьен', shortName: 'АМЬ', country: 'france' })
];

export const getClubTeams = createMapFn<ClubCompetition, Array<ClubTeam>>({
  england: englandClubs,
  germany: germanyClubs,
  spain: spainClubs,
  italy: italyClubs,
  france: franceClubs
});
